name: test_gpu
on: [push]
jobs:
  run:
    runs-on: [self-hosted,gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run:  |
          CODEBLOCK="\`\`\`"
          echo $CODEBLOCK > report.md
          nvidia-smi > report.md
          echo $CODEBLOCK > report.md
          cml-send-comment report.md
