name: test_gpu
on: [push]
jobs:
  run:
    runs-on: [self-hosted,cml,gpu]
    # optionally use a convenient Ubuntu LTS + CUDA + DVC + CML image
    # container: docker://dvcorg/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run:  |
          CODEBLOCK="\`\`\`"
          echo $CODEBLOCK > report.md
          nvidia-smi > report.md
          echo $CODEBLOCK > report.md
          cml-send-comment report.md
